apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irssh-panel-pvc
  namespace: production
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
