apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: irssh-panel-role-binding
  namespace: production
subjects:
- kind: ServiceAccount
  name: irssh-panel-sa
  namespace: production
roleRef:
  kind: Role
  name: irssh-panel-role
  apiGroup: rbac.authorization.k8s.io
