# roles/protocols/handlers/main.yml
---
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

# roles/protocols/handlers/main.yml
---
- name: restart xl2tpd
  systemd:
    name: xl2tpd
    state: restarted

- name: restart strongswan
  systemd:
    name: strongswan
    state: restarted

# ansible/roles/protocols/handlers/main.yml
---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart xl2tpd
  service:
    name: xl2tpd
    state: restarted

- name: restart strongswan
  service:
    name: strongswan
    state: restarted

- name: restart ocserv
  service:
    name: ocserv
    state: restarted

- name: restart wireguard
  service:
    name: wg-quick@wg0
    state: restarted

- name: restart singbox
  service:
    name: singbox
    state: restarted
---
- name: restart wireguard
  service:
    name: wg-quick@{{ wireguard_interface }}
    state: restarted
  listen: "restart wireguard service"

- name: reload wireguard
  shell: wg syncconf {{ wireguard_interface }} <(wg-quick strip {{ wireguard_interface }})
  listen: "reload wireguard config"

- name: reload sysctl
  command: sysctl -p
  listen: "reload sysctl settings"

- name: reload ufw
  service:
    name: ufw
    state: reloaded
  listen: "reload firewall rules"
