# roles/database/defaults/main.yml

# PostgreSQL version and installation
postgresql_version: "14"
postgresql_packages:
  - postgresql-{{ postgresql_version }}
  - postgresql-contrib
  - python3-psycopg2
  - libpq-dev

# Database configuration
db_name: "irssh_panel"
db_user: "irssh_admin"
db_password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"

# PostgreSQL configuration
postgresql_port: 5432
postgresql_listen_addresses: "localhost"
postgresql_max_connections: 100
postgresql_shared_buffers: "128MB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"
postgresql_effective_cache_size: "1GB"

# Backup configuration
backup_enabled: true
backup_directory: "/var/backups/postgresql"
backup_retention_days: 7
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Security settings
postgresql_ssl_enabled: true
postgresql_hba_entries:
  - type: local
    database: all
    user: postgres
    auth_method: peer
  - type: host
    database: all
    user: all
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: all
    user: all
    address: "::1/128"
    auth_method: md5

# Monitoring settings
postgresql_enable_monitoring: true
postgresql_exporter_enabled: false
postgresql_log_min_duration_statement: 1000  # ms
