groups:
- name: system
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage on {{ $labels.instance }}
      description: CPU usage is above 80% for more than 5 minutes

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage on {{ $labels.instance }}
      description: Memory usage is above 85% for more than 5 minutes

  - alert: DiskSpaceFilling
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Disk space filling up on {{ $labels.instance }}
      description: Disk usage is above 85% for more than 5 minutes

- name: application
  rules:
  - alert: HighResponseTime
    expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High response time on {{ $labels.instance }}
      description: Average response time is above 500ms for more than 5 minutes

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: High error rate on {{ $labels.instance }}
      description: Error rate is above 5% for more than 5 minutes

- name: database
  rules:
  - alert: PostgreSQLHighConnections
    expr: pg_stat_activity_count > pg_settings_max_connections * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High number of PostgreSQL connections
      description: Number of active connections is above 80% of max connections

  - alert: PostgreSQLSlowQueries
    expr: rate(pg_stat_activity_max_tx_duration{state="active"}[1m]) > 30
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Slow PostgreSQL queries detected
      description: Queries taking longer than 30 seconds detected

  - alert: RedisHighMemoryUsage
    expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Redis high memory usage
      description: Redis memory usage is above 80%

- name: networking
  rules:
  - alert: HighNetworkErrors
    expr: rate(node_network_transmit_errs_total[5m]) + rate(node_network_receive_errs_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Network errors detected on {{ $labels.instance }}
      description: Network interface errors detected in the last 5 minutes

  - alert: NetworkSaturation
    expr: (rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m])) / node_network_speed_bytes > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Network saturation on {{ $labels.instance }}
      description: Network utilization is above 80% for more than 5 minutes
