groups:
  - name: irssh_panel_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(irssh_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 10% for the last 5 minutes

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(irssh_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          description: 95th percentile latency is above 1 second

      - alert: HighConnectionCount
        expr: irssh_active_connections > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High connection count
          description: More than 1000 active connections

      - alert: ServiceDown
        expr: up{job="irssh-panel"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Service is down
          description: IRSSH Panel service is not responding

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_heap_size_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: Memory usage is above 80%

      - alert: DatabaseConnectionErrors
        expr: rate(irssh_database_connection_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Database connection errors
          description: Database connection errors detected

      - alert: ProtocolErrors
        expr: rate(irssh_protocol_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Protocol errors detected
          description: Protocol error rate is above 5%
