apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: production
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
  MONGO_REPLICA_SET_KEY: ${MONGODB_REPLICA_SET_KEY}
