apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: production
type: Opaque
stringData:
  username: admin
  password: ${MONGODB_PASSWORD}
  url: mongodb://admin:${MONGODB_PASSWORD}@mongodb-service:27017/irssh?authSource=admin
