---
- name: Add NodeSource repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  args:
    warn: false
  when: ansible_os_family == "Debian"

- name: Install Node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install global NPM packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - pm2
    - yarn
    - typescript
    - @types/node

- name: Configure NPM registry
  command: npm config set registry https://registry.npmjs.org/

- name: Set Node.js environment
  lineinfile:
    path: /etc/environment
    line: "NODE_ENV=production"
    state: present

- name: Configure PM2
  command: pm2 startup systemd
  args:
    creates: /etc/systemd/system/pm2-root.service

- name: Save PM2 process list
  command: pm2 save
  changed_when: false
