# roles/protocols/meta/main.yml
---
dependencies: []
galaxy_info:
  author: IRSSH Team
  description: SSH protocol configuration for IRSSH Panel
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        
# roles/protocols/meta/main.yml
---
dependencies: []
galaxy_info:
  author: IRSSH Team
  description: L2TP/IPSec protocol configuration for IRSSH Panel
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

# ansible/roles/protocols/meta/main.yml
---
galaxy_info:
  author: IRSSH Panel Team
  description: VPN Protocol Management Role
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
