apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: irssh-panel-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  tls:
  - hosts:
    - panel.example.com
    secretName: irssh-panel-tls
  rules:
  - host: panel.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: irssh-panel-service
            port:
              number: 80
