# playbooks/maintenance.yml

---
- name: IRSSH Panel System Maintenance
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check system requirements
      ansible.builtin.include_role:
        name: common
        tasks_from: check_requirements.yml

  roles:
    - role: common/update
      tags: ['update']
    
    - role: common/cleanup
      tags: ['cleanup']
    
    - role: database/backup
      tags: ['backup']
    
    - role: database/optimize
      tags: ['optimize']
    
    - role: protocols/check
      tags: ['protocols']

  tasks:
    - name: Check system services
      ansible.builtin.service_facts:
      register: service_state

    - name: Validate service status
      ansible.builtin.assert:
        that:
          - "service_state.ansible_facts.services['irssh-panel.service'].state == 'running'"
          - "service_state.ansible_facts.services['postgresql.service'].state == 'running'"
          - "service_state.ansible_facts.services['nginx.service'].state == 'running'"
        fail_msg: "Critical services are not running"
        success_msg: "All services are running correctly"

    - name: Check disk space
      ansible.builtin.shell: df -h /
      register: disk_space
      changed_when: false

    - name: Alert on low disk space
      ansible.builtin.debug:
        msg: "Warning: Low disk space on /"
      when: disk_space.stdout_lines[1].split()[-2].rstrip('%')|int > 85

    - name: Clean old logs
      ansible.builtin.shell: |
        find /var/log/irssh -name "*.log" -mtime +30 -delete
      args:
        executable: /bin/bash
      register: log_cleanup
      changed_when: log_cleanup.rc == 0

    - name: Clean temporary files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "/tmp/irssh-*"
        - "/tmp/backup-*"

    - name: Check protocol configurations
      ansible.builtin.shell: |
        for script in /opt/irssh-panel/modules/*-script.*; do
          if [ -x "$script" ]; then
            $script check || echo "Warning: $script check failed"
          fi
        done
      register: protocol_check
      changed_when: false

    - name: Update protocol ports if needed
      ansible.builtin.shell: |
        /opt/irssh-panel/modules/port-script.py optimize
      register: port_update
      changed_when: port_update.rc == 0

    - name: Generate system report
      ansible.builtin.template:
        src: templates/maintenance_report.j2
        dest: /var/log/irssh/maintenance-{{ ansible_date_time.date }}.log

  handlers:
    - name: Restart services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - irssh-panel
        - nginx

  post_tasks:
    - name: Send notification
      ansible.builtin.uri:
        url: "{{ telegram_webhook_url }}"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "Maintenance completed on {{ inventory_hostname }}"
      when: telegram_webhook_url is defined
