apm-server:
  host: "0.0.0.0:8200"
  secret_token: "your_secret_token"
  rum:
    enabled: true
    allow_origins: ['*']
    source_mapping:
      enabled: true

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  protocol: "https"
  username: "${ELASTIC_APM_USER}"
  password: "${ELASTIC_APM_PASSWORD}"
  ssl:
    certificate_authorities: ["/etc/apm-server/certs/ca.crt"]

setup.kibana:
  host: "https://kibana:5601"
  protocol: "https"
  username: "${ELASTIC_APM_USER}"
  password: "${ELASTIC_APM_PASSWORD}"
  ssl:
    certificate_authorities: ["/etc/apm-server/certs/ca.crt"]

logging:
  level: info
  to_files: true
  files:
    path: /var/log/apm-server
    name: apm-server
    rotateeverybytes: 10485760
    keepfiles: 7

monitoring:
  enabled: true
  elasticsearch:
    username: "${ELASTIC_APM_USER}"
    password: "${ELASTIC_APM_PASSWORD}"

queue.mem:
  events: 4096
  flush.min_events: 1024
  flush.timeout: "1s"

max_procs: 4

http:
  enabled: true
  host: "0.0.0.0"
  port: 8200
  ssl:
    enabled: true
    certificate: "/etc/apm-server/certs/apm.crt"
    key: "/etc/apm-server/certs/apm.key"
