---
- name: Configure Monitoring Stack
  hosts: monitoring_servers
  become: yes
  vars_files:
    - vars/monitoring.yml

  roles:
    - { role: prometheus, tags: ['prometheus'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: node_exporter, tags: ['node_exporter'] }
    - { role: alertmanager, tags: ['alertmanager'] }

  tasks:
    - name: Set up Prometheus
      template:
        src: templates/prometheus/{{ item }}.j2
        dest: "{{ prometheus_config_path }}/{{ item }}"
      with_items:
        - prometheus.yml
        - alerts.yml
        - recording_rules.yml
      notify: reload prometheus

    - name: Configure Grafana dashboards
      copy:
        src: files/grafana/dashboards/
        dest: "{{ grafana_dashboards_path }}/"
      notify: reload grafana

    - name: Set up alerting rules
      template:
        src: templates/alertmanager/{{ item }}.j2
        dest: "{{ alertmanager_config_path }}/{{ item }}"
      with_items:
        - config.yml
        - templates/email.tmpl
        - templates/slack.tmpl
      notify: reload alertmanager

    - name: Configure node exporters
      template:
        src: templates/node_exporter/config.yml.j2
        dest: "{{ node_exporter_config_path }}/config.yml"
      notify: restart node_exporter

    - name: Set up monitoring authentication
      template:
        src: templates/nginx/monitoring_auth.conf.j2
        dest: "{{ nginx_config_path }}/monitoring_auth.conf"
      notify: reload nginx

  handlers:
    - name: reload prometheus
      systemd:
        name: prometheus
        state: reloaded

    - name: reload grafana
      systemd:
        name: grafana-server
        state: reloaded

    - name: reload alertmanager
      systemd:
        name: alertmanager
        state: reloaded

    - name: restart node_exporter
      systemd:
        name: node_exporter
        state: restarted

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
