apiVersion: v1
kind: ConfigMap
metadata:
  name: irssh-panel-config
  namespace: production
data:
  config.yaml: |
    app:
      name: IRSSH Panel
      version: 1.0.0
    server:
      port: 3000
      host: 0.0.0.0
    logging:
      level: info
      format: json
    metrics:
      enabled: true
      port: 9090
    features:
      authentication: true
      authorization: true
      monitoring: true
