apiVersion: apps/v1
kind: Deployment
metadata:
  name: irssh-panel
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: irssh-panel
  template:
    metadata:
      labels:
        app: irssh-panel
    spec:
      containers:
      - name: irssh-panel
        image: registry.example.com/irssh-panel:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: secrets-volume
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: irssh-panel-config
      - name: secrets-volume
        secret:
          secretName: irssh-panel-secrets
