apiVersion: v1
kind: Service
metadata:
  name: irssh-panel
  namespace: production
  labels:
    app: irssh-panel
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: irssh-panel
