metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
  enabled: true
  period: 10s
  processes: ['.*']

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s
  hosts: ["http://nginx:80"]

- module: postgresql
  metricsets:
    - database
    - bgwriter
    - activity
  period: 10s
  hosts: ["postgres://postgres:your_password@postgresql:5432?sslmode=disable"]

- module: redis
  metricsets: ["info", "keyspace"]
  period: 10s
  hosts: ["redis://redis:6379"]
  password: "your_password"

processors:
- add_host_metadata: ~
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "https"
  username: "elastic"
  password: "your_password"
  ssl.certificate_authorities: ["certs/ca.crt"]

setup.kibana:
  host: "kibana:5601"
  protocol: "https"
  ssl.certificate_authorities: ["certs/ca.crt"]
