---
- name: Install security packages
  apt:
    name:
      - fail2ban
      - ufw
      - auditd
      - apparmor
      - apparmor-utils
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Configure UFW
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH connections
  ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Configure SSH hardening
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh

- name: Configure system limits
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf

- name: Configure auditd rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
  notify: restart auditd

- name: Enable and configure AppArmor
  command: aa-enforce system_policy
  notify: restart apparmor
