# roles/protocols/defaults/main.yml
---
# SSH Configuration
ssh_port: 22
ssh_password_auth: yes
ssh_user_dir: /etc/ssh/users
ssh_allowed_groups:
  - ssh-users
  - sudo

# roles/protocols/defaults/main.yml
---
# L2TP Configuration
l2tp_ip_range_start: 10.10.10.100
l2tp_ip_range_end: 10.10.10.200
l2tp_local_ip: 10.10.10.1
l2tp_ip_range: 10.10.10.0/24
l2tp_dns_1: 8.8.8.8
l2tp_dns_2: 8.8.4.4
ipsec_psk: "your_pre_shared_key"

# ansible/roles/protocols/defaults/main.yml
---
# Default protocol ports
ssh_port: 22
l2tp_port: 1701
ikev2_port: 500
cisco_port: 443
wireguard_port: 51820
singbox_port: 8388

# Cisco AnyConnect specific defaults
cisco_anyconnect:
  max_clients: 10
  max_same_clients: 2
  server_cert: "/etc/ocserv/server-cert.pem"
  server_key: "/etc/ocserv/server-key.pem"
  dh_params: "/etc/ocserv/dh.pem"
  auth_method: "password"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  routes: []
  no_routes: []

# roles/wireguard/defaults/main.yml
---
wireguard_port: 51820
wireguard_interface: wg0
wireguard_address: "10.8.0.1/24"
wireguard_network: "10.8.0.0/24"
wireguard_persistent_keepalive: 25
wireguard_save_config: true
wireguard_dns_servers: ["1.1.1.1", "1.0.0.1"]
wireguard_mtu: 1420
wireguard_allowed_ips: ["0.0.0.0/0", "::/0"]
wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
wireguard_log_level: "info"
wireguard_max_clients: 50
wireguard_config_dir: "/etc/wireguard"
wireguard_client_configs_dir: "/etc/wireguard/clients"
wireguard_systemd_resolved_dns: false

# Security settings
wireguard_fwmark: "0xca6c"
wireguard_preshared_key_enabled: true
wireguard_key_bits: 4096

# Performance settings
wireguard_ufw_rules_enabled: true
wireguard_sysctl_settings_enabled: true
wireguard_fail2ban_enabled: true
wireguard_monitoring_enabled: true

# Backup settings
wireguard_backup_enabled: true
wireguard_backup_dir: "/opt/irssh-panel/backups/wireguard"
wireguard_backup_retention: 7

# Module integration
irssh_panel_integration: true
irssh_panel_api_enabled: true
irssh_panel_metrics_enabled: true
---
# WireGuard Interface Configuration
wireguard_interface: wg0
wireguard_port: 51820
wireguard_address: 10.10.0.1/24
wireguard_mtu: 1420

# Server Configuration
wireguard_private_key_path: /etc/wireguard/privatekey
wireguard_public_key_path: /etc/wireguard/publickey
wireguard_preshared_key_path: /etc/wireguard/preshared

# Network Configuration
wireguard_allowed_ips: "10.10.0.0/24"
wireguard_dns_servers: ["8.8.8.8", "8.8.4.4"]
wireguard_persistent_keepalive: 25

# Performance Settings
wireguard_fwmark: 0xca6c
wireguard_save_config: true
wireguard_table: off

# Security Settings
wireguard_disable_ipv6: true
wireguard_post_up: "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
wireguard_post_down: "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"

# ansible/roles/protocols/defaults/main.yml

# Global settings
protocols_enabled:
  - ssh
  - l2tp
  - ikev2
  - cisco
  - wireguard
  - singbox

monitoring_interval: 60
log_retention_days: 30
backup_enabled: true

# SSH Configuration
ssh_port: 22
ssh_max_auth_tries: 3
ssh_password_auth: false
ssh_root_login: false
ssh_banner_enabled: true

# L2TP/IPSec
l2tp_port: 1701
ipsec_psk: "{{ vault_ipsec_psk }}"
l2tp_local_ip: "10.10.10.1"
l2tp_ip_range: "10.10.10.100-10.10.10.200"

# IKEv2
ikev2_port: 500
ikev2_natt_port: 4500
ikev2_cipher_suite: "aes256gcm16-prfsha512-ecp384"
ikev2_dns_servers:
  - 8.8.8.8
  - 8.8.4.4

# Cisco AnyConnect
cisco_port: 443
cisco_dpd_timeout: 60
cisco_max_clients: 100
cisco_cert_path: "/etc/ocserv/server-cert.pem"
cisco_key_path: "/etc/ocserv/server-key.pem"

# WireGuard
wg_port: 51820
wg_interface: "wg0"
wg_address: "10.20.30.1/24"
wg_mtu: 1420
wg_persistent_keepalive: 25

# SingBox Configuration
singbox:
  shadowsocks:
    enabled: true
    port: 8388
    method: "chacha20-ietf-poly1305"
  tuic:
    enabled: true
    port: 8443
    congestion_control: "bbr"
  vless:
    enabled: true
    port: 443
    flow: "xtls-rprx-vision"
  hysteria2:
    enabled: true
    port: 8080
    up_mbps: 100
    down_mbps: 100
