# roles/protocols/defaults/main.yml
---
# SSH Configuration
ssh_port: 22
ssh_password_auth: yes
ssh_user_dir: /etc/ssh/users
ssh_allowed_groups:
  - ssh-users
  - sudo

# roles/protocols/defaults/main.yml
---
# L2TP Configuration
l2tp_ip_range_start: 10.10.10.100
l2tp_ip_range_end: 10.10.10.200
l2tp_local_ip: 10.10.10.1
l2tp_ip_range: 10.10.10.0/24
l2tp_dns_1: 8.8.8.8
l2tp_dns_2: 8.8.4.4
ipsec_psk: "your_pre_shared_key"

# ansible/roles/protocols/defaults/main.yml
---
# Default protocol ports
ssh_port: 22
l2tp_port: 1701
ikev2_port: 500
cisco_port: 443
wireguard_port: 51820
singbox_port: 8388

# Cisco AnyConnect specific defaults
cisco_anyconnect:
  max_clients: 10
  max_same_clients: 2
  server_cert: "/etc/ocserv/server-cert.pem"
  server_key: "/etc/ocserv/server-key.pem"
  dh_params: "/etc/ocserv/dh.pem"
  auth_method: "password"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  routes: []
  no_routes: []
