# roles/protocols/defaults/main.yml
---
# SSH Configuration
ssh_port: 22
ssh_password_auth: yes
ssh_user_dir: /etc/ssh/users
ssh_allowed_groups:
  - ssh-users
  - sudo

# roles/protocols/defaults/main.yml
---
# L2TP Configuration
l2tp_ip_range_start: 10.10.10.100
l2tp_ip_range_end: 10.10.10.200
l2tp_local_ip: 10.10.10.1
l2tp_ip_range: 10.10.10.0/24
l2tp_dns_1: 8.8.8.8
l2tp_dns_2: 8.8.4.4
ipsec_psk: "your_pre_shared_key"

# ansible/roles/protocols/defaults/main.yml
---
# Default protocol ports
ssh_port: 22
l2tp_port: 1701
ikev2_port: 500
cisco_port: 443
wireguard_port: 51820
singbox_port: 8388

# Cisco AnyConnect specific defaults
cisco_anyconnect:
  max_clients: 10
  max_same_clients: 2
  server_cert: "/etc/ocserv/server-cert.pem"
  server_key: "/etc/ocserv/server-key.pem"
  dh_params: "/etc/ocserv/dh.pem"
  auth_method: "password"
  dns_servers:
    - "8.8.8.8"
    - "8.8.4.4"
  routes: []
  no_routes: []

# roles/wireguard/defaults/main.yml
---
wireguard_port: 51820
wireguard_interface: wg0
wireguard_address: "10.8.0.1/24"
wireguard_network: "10.8.0.0/24"
wireguard_persistent_keepalive: 25
wireguard_save_config: true
wireguard_dns_servers: ["1.1.1.1", "1.0.0.1"]
wireguard_mtu: 1420
wireguard_allowed_ips: ["0.0.0.0/0", "::/0"]
wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
wireguard_log_level: "info"
wireguard_max_clients: 50
wireguard_config_dir: "/etc/wireguard"
wireguard_client_configs_dir: "/etc/wireguard/clients"
wireguard_systemd_resolved_dns: false

# Security settings
wireguard_fwmark: "0xca6c"
wireguard_preshared_key_enabled: true
wireguard_key_bits: 4096

# Performance settings
wireguard_ufw_rules_enabled: true
wireguard_sysctl_settings_enabled: true
wireguard_fail2ban_enabled: true
wireguard_monitoring_enabled: true

# Backup settings
wireguard_backup_enabled: true
wireguard_backup_dir: "/opt/irssh-panel/backups/wireguard"
wireguard_backup_retention: 7

# Module integration
irssh_panel_integration: true
irssh_panel_api_enabled: true
irssh_panel_metrics_enabled: true
---
# WireGuard Interface Configuration
wireguard_interface: wg0
wireguard_port: 51820
wireguard_address: 10.10.0.1/24
wireguard_mtu: 1420

# Server Configuration
wireguard_private_key_path: /etc/wireguard/privatekey
wireguard_public_key_path: /etc/wireguard/publickey
wireguard_preshared_key_path: /etc/wireguard/preshared

# Network Configuration
wireguard_allowed_ips: "10.10.0.0/24"
wireguard_dns_servers: ["8.8.8.8", "8.8.4.4"]
wireguard_persistent_keepalive: 25

# Performance Settings
wireguard_fwmark: 0xca6c
wireguard_save_config: true
wireguard_table: off

# Security Settings
wireguard_disable_ipv6: true
wireguard_post_up: "iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
wireguard_post_down: "iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE"
