# roles/protocols/vars/main.yml
---
ssh_host_key_algorithms:
  - ssh-ed25519
  - rsa-sha2-512
  - rsa-sha2-256

ssh_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com

ssh_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com

# Vars/main.yml
---
enabled_protocols:
  - ssh
  - l2tp
  - ikev2
  - cisco
  - wireguard
  - singbox

vpn_users: []  # Will be populated by the panel

# ansible/roles/protocols/vars/main.yml
---
ocserv_packages:
  - ocserv
  - gnutls-bin
  - iptables-persistent

certificate_info:
  country: US
  state: State
  locality: City
  organization: IRSSH Panel
  common_name: "{{ ansible_fqdn }}"
  email: admin@example.com
  
